services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    image: php:8.1-apache
    container_name: php_container
    volumes:
      - '.:/var/www/html'
      - ./public:/var/www/html
      - ./app:/var/www/app
      - ./config:/var/www/config
      - ./resources:/var/www/resources
      - ./routes:/var/www/routes
      - ./vendor:/var/www/vendor
      - ./apache.conf:/etc/apache2/conf-enabled/servername.conf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "8080:80"
    networks:
      - mynetwork
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password   # Define a senha do usuário root
      MYSQL_DATABASE: mydatabase      # Opcional: criar um banco de dados inicial
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql_container
      MYSQL_ROOT_PASSWORD: password  # Deve corresponder à senha do root configurada
    ports:
      - "8081:80"
    networks:
      - mynetwork
networks:
  mynetwork:
volumes:
  mysql_data:
